
% see also: cnf_order2.pl

cnf_compare( CNF1, CNF2) :- true
, cnf_maplist_msort_order_index( CNF1, _CNF1_GROUP, CNF1_GROUP_ORDER, CNF1_GROUP_ORDERED)
, cnf_maplist_msort_order_index( CNF2, _CNF2_GROUP, CNF2_GROUP_ORDER, CNF2_GROUP_ORDERED)
, CNF1_GROUP_ORDERED == CNF2_GROUP_ORDERED
, sorted_to_permutation_indicator0( CNF1_GROUP_ORDERED, PERMUTATION_CLASS_IDS)
, index0( CNF1_GROUP_ORDER, CNF1, CNF1_ORDERED)
, index0( CNF2_GROUP_ORDER, CNF2, CNF2_ORDERED)
, interpermutation( PERMUTATION_CLASS_IDS, CNF2_ORDERED, CNF3_ORDERED)
, transposed_msort( CNF1_ORDERED, CNF1_ORDERED_TMSORT)
, transposed_msort( CNF3_ORDERED, CNF3_ORDERED_TMSORT)
, CNF1_ORDERED_TMSORT == CNF3_ORDERED_TMSORT
.

