
:- use_module( library(clpb)). % ~, *([]), +([]), sat, labeling
:- use_module( library(clpfd)). % transpose
:- use_module( library(error)). % must_be

:- set_prolog_flag( stack_limit , 10_737_418_240).
% :- set_prolog_flag( table_space, 10_737_418_240).
:- set_prolog_flag( table_space, 20_737_418_240).
:- set_prolog_flag( answer_write_options, [quoted(true), portray(true), max_depth(250), spacing(next_argument)]).


:- consult( 'tools/combine.pl').
:- consult( 'tools/order.pl').
:- consult( 'tools/permutation.pl').

:- consult( 'create_cnf.pl').
:- consult( 'create_cnf_all.pl').

:- consult( 'helper.pl').

:- consult( 'cnf_compare.pl').

:- consult( 'cnf_order1.pl').

:- consult( 'cnf_order2.pl').

:- consult( 'cnf_minpermutation.pl').

:- consult( 'cnf_only_minpermutation.pl').

:- consult( 'group_sorted_cnf_table.pl').

:- consult( 'benchmark.pl').

show_raising_rows( VARCOUNT) :- true
, forall( between( 1, inf, RULECOUNT), ( true
   , aggregate_all( count, cnf_only_minpermutation3( RULECOUNT, VARCOUNT, _CNF), COUNT)
   , write( COUNT)
   , write( ', ')
   , flush_output
   , COUNT \== 0
   ) 
  )
.

/*

% https://oeis.org/search?q=0%2C+0%2C+3%2C+3%2C+1%2C+0&language=english&go=Search # 0, 0, 3, 3, 1, 0
% 
% (ins)?- show_raising_rows( 1).
% 3, 3, 1, 0
% false.
% 
% 
% (ins)?- show_raising_rows( 2).
% 6, 21, 47, 69, 69, 47, 21, 6, 1, 0
% false.

% (ins)?- show_raising_rows( 3).
% 10, 82, 573, 3176, 14066, 50646, 150508, 
% ERROR: '$tbl_wkl_add_answer'/4: Not enough resources: private_table_space

% (ins)?- show_raising_rows( 4).
% 15, 252, 4558, 76545, ^C

% (ins)?- show_raising_rows( 5). % 70% hauptspeichernutzung (von 32Gig)
% 21, 657, ^C


*/

show_raising_vars( RULECOUNT, MAXVARCOUNT) :- true
, forall( between( 0, MAXVARCOUNT, VARCOUNT), ( true
   , aggregate_all( count, cnf_only_minpermutation3( RULECOUNT, VARCOUNT, _CNF), COUNT)
   , write( COUNT)
   , write( ', ')
   , flush_output
   )
  )
.

/*

% (ins)?- show_raising_vars( 1, 10).
% 0, 3, 6, 10, 15, 21, 28, 36, 45, 55, 66 # A253145 Triangular numbers (A000217) omitting the term 1.


% (ins)?- show_raising_vars( 2, 10).
% 0, 3, 21, 82, 252, 657, 1533, 3276, ^C

% (ins)?- show_raising_vars( 3, 5).
% 0, 1, 47, 573, 4558, 28643
% true.

% (cmd)?- show_raising_vars( 4, 4).
% 0, 0, 69, 3176, 76545
% true.

% (cmd)?- show_raising_vars( 5, 3).
% 0, 0, 69, 14066, 
% true.

% (ins)?- show_raising_vars( 6, 3).
% 0, 0, 47, 50646, 
% true.

% (cmd)?- show_raising_vars( 7, 3).
% 0, 0, 21, , 150508, 
% true.

*/

/*

% interesting oeis entries
% 
% https://oeis.org/search?q=cnf&language=english&go=Search
% 
% https://oeis.org/A112650 # A112650 Number of truth tables generated by (n-1)-CNF Boolean expressions of n variables.
% 
% 
% https://oeis.org/A112535 # A112535 Number of truth tables generated by 3CNF expressions of n variables.
% 
% ...

*/

% rule_sat( ASSOC_IN, CNF, SAT, ASSOC_OUT) :- true
% , 

% cnf_sat( ASSOC, CNF, SAT) :- true

:- consult( 'cnf_clpb/rule_freevars.pl').
:- consult( 'cnf_clpb/cnf_freevars.pl').
:- consult( 'cnf_clpb/cnf_sat.pl').
:- consult( 'cnf_clpb/cnf_solutioncount.pl').
:- consult( 'cnf_clpb/cnf_solutioncount_count.pl').
:- consult( 'cnf_clpb/cnf_solutioncount_count_sequence.pl').

